### ISSUE TITLE
Regression in 0.7.1 for actix web & tail matches

### ISSUE THREAD

**Issue by cetra3** [paperclip-rs/paperclip#453]
Looks like there has been a change to the way url path parameters are generated between `0.7.0` & `0.7.1`.  When using a tail match, which is normally defined by with a `{param:.*}` in the url, this now has broken output.

Here's an example config:

```rust
cfg.service(web::resource("/example/{filename:.*}").route(web::get().to(get_example)))
```

This matches anything that has the `/example/` prefix, including any extra slashes etc..

Here's a diff of a service:

```diff
     "/example/{filename:.*}": {
       "get": {
         "operationId": "get_example",
         "parameters": [
           {
             "in": "path",
-            "name": "filename:.*",
+            "name": "filename",
             "required": true,
             "schema": {
               "type": "string"
             },
             "style": "simple"
           },
```

I would expect in this case the name still is `filename:.*`

**Comment by tiagolobocastro** [comment]
Looks like this was done by #430

**Comment by tiagolobocastro** [comment]
@cetra3 it this is what's happening then I think current behaviour is wrong because it leads to invalid openapi (easy to check on openapi website editor)
@snaggen any thoughts here?

**Comment by tiagolobocastro** [comment]
Yeah the problem is that the filename on the path differers, so this yields invalid spec :(

Since there is nothing on the spec about regex being valid or other I think we should keep it as it was before.
I also use regex in the openapi at work, and I've yet to see an issue with the openapi tools.

We can add a option to keep or remove regex? But when the option is set to remove, remove it from the path as well.

What do you think?

**Comment by snaggen** [comment]
I would have thought, stripping the regex out of the path and adding it as a pattern in the schema would be most correct. 

Keeping the regex on the name causes it to be visible to users in documentation as part of the name. This is not a huge problem, just a bit ugly.

**Comment by snaggen** [comment]
In the example diff in OP , there are a schema section. A schema section can contain a pattern, which should be a regex. So, by moving the regex from the path and name, to the schema (in the pattern property) we should get the same semantics as the actix path syntax.

**Comment by tiagolobocastro** [comment]
You mean like:
```
type: string
pattern: ".*"
```

Interestingly on the spec Format it says the following:
"The schema exposes two types of fields: Fixed fields, which have a declared name, and Patterned fields, which declare a regex pattern for the **field name**.

So it seems a field name can be a regex?

**Comment by snaggen** [comment]
Well, under the Path section for Patterned Fields, it doesn't mention anything about regex at all.... it seems to just mean the `/some/{path}` syntax. And also, the Patterned Fields refer to matching the path to use, not to restrict it like actix does, so it is a very different semantics.
```json
     "/example/{filename}": {
       "get": {
         "operationId": "get_example",
         "parameters": [
           {
             "in": "path",
            "name": "filename",
             "required": true,
             "schema": {
               "type": "string",
               "pattern": ".*"
             },
             "style": "simple"
           },
```
is how I think the actix route 
```rust
cfg.service(web::resource("/example/{filename:.*}").route(web::get().to(get_example)))
```
should be interpreted since in actix this means the path /example/{filename} that matches ".**

**Comment by tiagolobocastro** [comment]
Yeah I'd be happy with that. @cetra3 looks good to you too?

How would we do reversal to generate server side code from that yaml? Only if the pattern is explicitly ".*" do we pass that to the actix server?

**Comment by snaggen** [comment]
> How would we do reversal to generate server side code from that yaml? Only if the pattern is explicitly ".*" do we pass that to the actix server?
Well, since the pattern is regex shouldn't it just be reversed, so that the path would be `/example/{name:pattern}` in any case where the schema have a pattern?

**Comment by tiagolobocastro** [comment]
Oh ok I thought actix didn't quite support regex, it's been a while since I looked at it.

**Comment by cetra3** [comment]
So to expand upon the issue a little more, we're using the [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) which does a pretty trivial "search & replace" against the path to build up the correct uri.  With `0.7.1` this doesn't work, as `filename:.*` != `filename`.

To clarify: in actix-web this syntax is [not strictly regex](https://github.com/actix/actix-web/blob/cc7145d41dd75beb61ee1882ba677c20d5f1fd76/actix-router/src/resource.rs#L897-L950), it's a special way of dictating a path route includes a tail match. That is: the param can include forward slashes.

I.e, `/example/{filename:.*}` matches on:

```
/example/file.txt
/example/path/to/file.txt
/example/another/file.txt
```

Whereas `/example/{filename}` only matches things like:

```
/example/file.txt
/example/another_file.txt
```

So I think this statement might not be entirely correct:

>should be interpreted since in actix this means the path /example/{filename} where the filename matches ".**

**However:** I agree that the example given example looks like it would solve the issue.

**Comment by snaggen** [comment]
I took a stab at fixing the regression, but got stuck. Basically, one way to do it would be to strip the pattern as early as possible. So, that nothing that goes in to path_map contains a pattern. However, then we loose the information about the pattern. So, I guess the pattern should be removed as late as possible, but I'm not sure how to do that in a good way.

**Comment by snaggen** [comment]
I have now pushed a fix for this regression. The pattern in the template is removed when the paths is serialized. And the pattern is also set as a pattern in the parameter information. 
I realize that the patterns might not be fully compatible, but it will probably only be a problem in the more advanced cases. So, perhaps just wait and address that when it becomes a problem.

**Comment by cetra3** [comment]
Hey looks like this one is still an issue in `0.8.1` should I raise another issue or can we reopen this one.

**Comment by tiagolobocastro** [comment]
Oh then let's reopen it :(

**Comment by snaggen** [comment]
@cetra3 When I look at the generated spec file, things look as expected. Can you provide an example where this breaks in current paperclip, and I can have a look.
